---
# file: roles/deploy/tasks/main.yml
- name: Create rtorrent directories
  file: path={{ item }} state=directory
  with_items:
    - "{{ home }}/rtorrent"
    - "{{ home }}/rtorrent/session"
    - "{{ home }}/rtorrent/watch"
    - "{{ home }}/rtorrent/download"

- name: Deploy default rtorrent config
  template: src=rtorrent.rc.j2 dest={{ home }}/.rtorrent.rc

- name: Depoly rutorrent
  command: rsync -a {{ contrib }}/{{ dir_rutorrent }} /var/www
  sudo: yes

- name: Deploy rutorrent plugins
  command: rsync -a {{ contrib }}/{{ dir_ruplugins }} /var/www/plugins
  sudo: yes
