---
- hosts: ec2
  vars: 
    home: /home/ubuntu
    contrib: /home/ubuntu/contrib
    src_libtorrent: http://libtorrent.rakshasa.no/downloads/
    ver_libtorrent: libtorrent-0.13.2
    src_rtorrent: http://libtorrent.rakshasa.no/downloads/
    ver_rtorrent: rtorrent-0.9.2
    src_rutorrent: https://rutorrent.googlecode.com/files/
    ver_rutorrent: rutorrent-3.5
    dir_rutorrent: rutorrent
    src_ruplugins: https://rutorrent.googlecode.com/files/
    ver_ruplugins: plugins-3.5
    dir_ruplugins: plugins
    dir_xmlrpc: xmlrpc-c
    port_range: 6666-9999
    scgi_addr: localhost:5000
  vars_prompt:
  - name: rutorrent_user
    prompt: "rutorrent user"
    private: no
  - name: rutorrent_password
    prompt: "rutorrent password"
    private: yes
    encrypt: "md5_crypt"
    confirm: yes
    salt_size: 7
  tasks:
  - apt: name={{ item }} state=installed update_cache=yes cache_valid_time=3600
    with_items: 
      - subversion
      - build-essential
      - automake
      - libtool
      - libcppunit-dev
      - libsigc++-2.0-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - unzip
      - unrar-free
      - curl
      - libncurses5-dev
      - apache2
      - php5
      - php5-cli
      - php5-curl
      - libapache2-mod-scgi
    sudo: yes
  - file: path={{ contrib }} state=directory
  - subversion: dest={{ contrib }}/{{ dir_xmlrpc }} repo=http://xmlrpc-c.svn.sourceforge.net/svnroot/xmlrpc-c/stable
  - get_url: dest={{ contrib}} url={{ item }}.tar.gz
    with_items:
      - "{{ src_libtorrent }}{{ ver_libtorrent }}"
      - "{{ src_rtorrent }}{{ ver_rtorrent }}"
      - "{{ src_rutorrent }}{{ ver_rutorrent }}"
      - "{{ src_ruplugins }}{{ ver_ruplugins }}"
  - command: tar xvf {{ ver_libtorrent }}.tar.gz  chdir={{contrib}} creates={{ ver_libtorrent }}
  - command: tar xvf {{ ver_rtorrent }}.tar.gz  chdir={{contrib}} creates={{ ver_rtorrent }}
  - command: tar xvf {{ ver_rutorrent }}.tar.gz  chdir={{contrib}} creates={{ dir_rutorrent }}
  - command: tar xvf {{ ver_ruplugins }}.tar.gz  chdir={{contrib}} creates={{ dir_ruplugins }}

  - name: Build and Install xmlrpc
    command: chdir={{ contrib }}/{{ dir_xmlrpc }} {{ item }} creates=/usr/local/bin/xmlrpc-c-config
    sudo: yes
    with_items:
      - ./configure --disable-cplusplus
      - make 
      - make install

  - name: Build and Install libtorrent
    command: chdir={{ contrib }}/{{ ver_libtorrent }} {{ item }} creates=/usr/bin/libtool
    sudo: yes
    with_items:
      - ./autogen.sh
      - ./configure
      - make 
      - make install 

  - name: Build and Install rtorrent
    command: chdir={{ contrib }}/{{ ver_rtorrent }} {{ item }} creates=/usr/local/bin/rtorrent
    sudo: yes
    with_items:
      - ./autogen.sh
      - ./configure --with-xmlrpc-c
      - make 
      - make install
      - ldconfig 
  
  - file: src=/etc/apache2/mods-available/scgi.load dest=/etc/apache2/mods-enabled/scgi.load state=link
    sudo: yes
    notify:
    - restart apache

  - name: Create rtorrent directories
    file: path={{ item }} state=directory
    with_items:
      - "{{ home }}/rtorrent"
      - "{{ home }}/rtorrent/session"
      - "{{ home }}/rtorrent/watch"
      - "{{ home }}/rtorrent/download"
  
  - name: Deploy default rtorrent config
    template: src=rtorrent.j2 dest={{ home }}/.rtorrent.rc

  - name: Deply rutorrent
    command: rsync -a {{ contrib }}/{{ dir_rutorrent }} /var/www
    sudo: yes

  - name: Deply rutorrent
    command: rsync -a {{ contrib }}/{{ dir_ruplugins }} /var/www/plugins
    sudo: yes

  - name: Add rutorrent user
    command: htpasswd -bc /etc/apache2/.htpasswd {{ rutorrent_user}} {{ rutorrent_password }} creates=/etc/apache2/.hthtpasswd
    sudo: yes

  - file: path=/etc/apache2/.htpasswd owner=root mode=0640
    sudo: yes

  handlers:
  - name: restart apache
    service: name=apache2 state=restarted
    sudo: yes
