---
# file: roles/deploy/tasks/main.yml
- name: Create rtorrent directories
  file: path={{ item }} state=directory
  with_items:
    - "{{ home }}/rtorrent"
    - "{{ home }}/rtorrent/session"
    - "{{ home }}/rtorrent/watch"
    - "{{ home }}/rtorrent/download"

- name: Deploy rutorrent
  command: rsync -a {{ contrib }}/{{ dir_rutorrent }}/ /var/www/rutorrent/
  sudo: yes

- name: Deploy rutorrent plugins
  command: rsync -a {{ contrib }}/{{ dir_ruplugins }}/ /var/www/rutorrent/plugins/
  sudo: yes

- file: path=/var/www/rutorrent/ 
        state=directory 
        recurse=yes
        owner={{ apache_user }} 
        group={{ apache_user }} 
  sudo: yes
