---
# file: roles/config/tasks/main.ym;

- name: Deploy default rtorrent config
  template: 
    src=rtorrent.rc.j2 
    dest={{ home }}/.rtorrent.rc

- name: Enable scgi for ru/r connectivity
  file: 
    src=/etc/apache2/mods-available/scgi.load 
    dest=/etc/apache2/mods-enabled/scgi.load 
    state=link
  sudo: yes
  notify:
  - restart apache

- name: Create rupasswd file
  htpasswd: 
    path={{ ru_passwd_file }}
    name={{ ru_user }} 
    password={{ ru_password }}
    state=present
    owner=root
    group=www-data
    mode=0640
  sudo: yes

- name: Remove default sites-enabled
  file: path=/etc/apache2/sites-enabled/000-default state=absent
  sudo: yes

- name: Create rutorrent virtual directory
  template:
    src=rutorrent.j2
    dest=/etc/apache2/sites-enabled/rutorrent
    owner=root
    group=root
  sudo: yes

- name: Enable rutorrent site
  command: a2ensite rutorrent
  sudo: yes
  notify:
    - restart apache
